#!/usr/bin/env tsx
// Why: JSON만 고치고 `generate:from-registry`를 안 돌린 DECISION_IDS 드리프트를 PR에서 차단.
/**
 * decision-registry.json 의 decisions[].id 순서·목록과
 * packages/lib/core/decisions/index.ts (`<auto-generated-decision-ids>` 구간) 의 DECISION_IDS 가 일치하는지 검증.
 * JSON만 고치고 `pnpm run generate:from-registry` 를 안 돌린 드리프트를 PR에서 차단.
 */
import * as fs from 'fs';
import * as path from 'path';

const ROOT = path.resolve(__dirname, '..', '..', '..');
const GENERATED_PATH = path.join(ROOT, 'packages', 'lib', 'core', 'decisions', 'index.ts');

function getRegistryPath(): string {
  const arg = process.argv.find((a) => a.startsWith('--registry='));
  if (arg) return path.resolve(ROOT, arg.slice('--registry='.length).trim());
  const env = process.env.CONSTITUTION_REGISTRY_PATH;
  if (env) return path.resolve(ROOT, env);
  const itemwiki = path.join(ROOT, 'docs', 'itemwiki-constitution', 'decision-registry.json');
  if (fs.existsSync(itemwiki)) return itemwiki;
  return path.join(ROOT, 'docs', 'constitution', 'decision-registry.json');
}

interface Decision {
  id: string;
}

interface Registry {
  decisions: Decision[];
}

function loadIdsFromRegistry(registryPath: string): string[] {
  const raw = fs.readFileSync(registryPath, 'utf-8');
  const data = JSON.parse(raw) as Registry;
  if (!Array.isArray(data.decisions)) {
    throw new Error('[check:decision-registry-generated-sync] registry.decisions 배열이 아님');
  }
  return data.decisions.map((d) => d.id);
}

function loadIdsFromGenerated(generatedPath: string): string[] {
  if (!fs.existsSync(generatedPath)) {
    throw new Error(`[check:decision-registry-generated-sync] 파일 없음: ${generatedPath}`);
  }
  const src = fs.readFileSync(generatedPath, 'utf-8');
  const m = src.match(/export const DECISION_IDS = (\[[\s\S]*?\])\s*as const/);
  if (!m?.[1]) {
    throw new Error(
      '[check:decision-registry-generated-sync] index.ts 에서 DECISION_IDS 배열을 파싱할 수 없음'
    );
  }
  try {
    const parsed = JSON.parse(m[1]) as unknown;
    if (!Array.isArray(parsed) || !parsed.every((x) => typeof x === 'string')) {
      throw new Error('not string[]');
    }
    return parsed as string[];
  } catch {
    throw new Error(
      '[check:decision-registry-generated-sync] DECISION_IDS 배열 JSON 파싱 실패 — generate-from-registry 출력 형식을 확인하세요'
    );
  }
}

function main(): void {
  const registryPath = getRegistryPath();
  if (!fs.existsSync(registryPath)) {
    console.error('[check:decision-registry-generated-sync] decision-registry.json 없음:', registryPath);
    process.exit(1);
  }

  const fromJson = loadIdsFromRegistry(registryPath);
  let fromFile: string[];
  try {
    fromFile = loadIdsFromGenerated(GENERATED_PATH);
  } catch (e) {
    console.error(e instanceof Error ? e.message : e);
    process.exit(1);
  }

  if (fromJson.length !== fromFile.length) {
    console.error(
      `[check:decision-registry-generated-sync] 개수 불일치: registry.json ${fromJson.length}개 vs index.ts ${fromFile.length}개`
    );
    console.error('\n조치: pnpm run generate:from-registry');
    process.exit(1);
  }

  const mismatches: { index: number; json: string; generated: string }[] = [];
  for (let i = 0; i < fromJson.length; i++) {
    if (fromJson[i] !== fromFile[i]) {
      mismatches.push({ index: i, json: fromJson[i]!, generated: fromFile[i]! });
    }
  }

  if (mismatches.length > 0) {
    console.error(
      `[check:decision-registry-generated-sync] 순서 또는 값 불일치 ${mismatches.length}건 (처음 몇 건만 표시):`
    );
    for (const row of mismatches.slice(0, 15)) {
      console.error(
        `  - [${row.index}] json="${row.json}" generated="${row.generated}"`
      );
    }
    if (mismatches.length > 15) {
      console.error(`  ... 외 ${mismatches.length - 15}건`);
    }
    console.error('\n조치: pnpm run generate:from-registry');
    process.exit(1);
  }

  console.log(
    `[check:decision-registry-generated-sync] OK — ${fromJson.length} id(s) match ${path.relative(ROOT, registryPath)} ↔ packages/lib/core/decisions/index.ts`
  );
}

main();
