#!/usr/bin/env tsx
/**
 * Registry 기반 코드 생성기 (Constitution 디렉터리 내 스크립트)
 *
 * decision-registry.json을 읽어 constitution/generated/registry-generated.ts 를 생성.
 * Itemwiki: packages/lib/core/decisions/index.ts 의 `// <auto-generated-decision-ids>` 구간도 동일 본문으로 갱신한다.
 *
 * 사용:
 *   tsx docs/constitution/scripts/generate-from-registry.ts
 */

import * as fs from 'fs';
import * as path from 'path';

const CONSTITUTION_DIR = path.resolve(__dirname, '..');
const ROOT = path.resolve(__dirname, '..', '..', '..');
const DEFAULT_OUTPUT = path.join(CONSTITUTION_DIR, 'generated', 'registry-generated.ts');

function getRegistryPath(): string {
  const arg = process.argv.find((a) => a.startsWith('--registry='));
  if (arg) return path.resolve(ROOT, arg.slice('--registry='.length).trim());
  const env = process.env.CONSTITUTION_REGISTRY_PATH;
  if (env) return path.resolve(ROOT, env);
  const itemwiki = path.join(ROOT, 'docs', 'itemwiki-constitution', 'decision-registry.json');
  if (fs.existsSync(itemwiki)) return itemwiki;
  return path.join(CONSTITUTION_DIR, 'decision-registry.json');
}

interface Decision {
  id: string;
  title: string;
  singleSource: string;
  verificationScript?: string | null;
  layers?: string[];
}

interface Registry {
  version: string;
  decisions: Decision[];
}

const LIB_DECISIONS_INDEX = path.join(ROOT, 'packages', 'lib', 'core', 'decisions', 'index.ts');
const AUTO_GEN_START = '// <auto-generated-decision-ids>';
const AUTO_GEN_END = '// </auto-generated-decision-ids>';

function patchLibDecisionsIndex(content: string): void {
  if (!fs.existsSync(LIB_DECISIONS_INDEX)) return;
  const src = fs.readFileSync(LIB_DECISIONS_INDEX, 'utf-8');
  const i0 = src.indexOf(AUTO_GEN_START);
  const i1 = src.indexOf(AUTO_GEN_END);
  if (i0 === -1 || i1 === -1 || i1 <= i0) {
    console.warn('⚠️  packages/lib/core/decisions/index.ts 에 자동 생성 마커 없음 — 스킵');
    return;
  }
  const next =
    src.slice(0, i0 + AUTO_GEN_START.length) + '\n' + content + '\n' + src.slice(i1);
  fs.writeFileSync(LIB_DECISIONS_INDEX, next, 'utf-8');
  console.log(`✅ patched: ${path.relative(ROOT, LIB_DECISIONS_INDEX)} (<auto-generated-decision-ids>)`);
}

function main(): void {
  const REGISTRY_PATH = getRegistryPath();

  if (!fs.existsSync(REGISTRY_PATH)) {
    console.error('❌ decision-registry.json 없음:', REGISTRY_PATH);
    process.exit(1);
  }

  const registry = JSON.parse(fs.readFileSync(REGISTRY_PATH, 'utf-8')) as Registry;
  const ids = registry.decisions.map((d) => d.id);

  const lines: string[] = [
    '/**',
    ' * 결정 ID — decision-registry.json에서 자동 생성.',
    ' * 재생성: pnpm run generate:from-registry',
    ' * CI 검증: pnpm run check:decision-registry-generated-sync',
    ' */',
    '',
    `export const DECISION_IDS = ${JSON.stringify(ids, null, 2)} as const;`,
    '',
    `export type DecisionId = (typeof DECISION_IDS)[number];`,
    '',
    'export function isRegisteredDecisionId(id: string): id is DecisionId {',
    '  return (DECISION_IDS as readonly string[]).includes(id);',
    '}',
    '',
    `// 레지스트리 버전: ${registry.version}`,
    `// 결정 수: ${ids.length}`,
  ];

  const content = lines.join('\n');

  // 1) 항상 constitution/generated 에 생성 (이식 가능 단일 소스)
  const outDir = path.dirname(DEFAULT_OUTPUT);
  if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(DEFAULT_OUTPUT, content, 'utf-8');
  console.log(`✅ generated: ${path.relative(ROOT, DEFAULT_OUTPUT)}`);

  patchLibDecisionsIndex(content);

  console.log(`   결정 ID ${ids.length}개, 타입 DecisionId export`);
  process.exit(0);
}

main();
